# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4654bb92da30942909c9ed5af58fad8e"
name = "consolidated-demand-app"
handle = "consolidated-demand-app-11"
application_url = "https://borough-magnetic-least-machine.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "liz-dev-pre-pop-september.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://borough-magnetic-least-machine.trycloudflare.com/auth/callback",
  "https://borough-magnetic-least-machine.trycloudflare.com/auth/shopify/callback",
  "https://borough-magnetic-least-machine.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
